# Generated by Django 5.0.1 on 2025-05-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("linear", "Linear Data Structures"),
                            ("tree", "Tree Structures"),
                            ("graph", "Graph Structures"),
                            ("hash", "Hashing Structures"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("search", "Searching Algorithms"),
                            ("sort", "Sorting Algorithms"),
                            ("tree", "Tree Operations"),
                            ("graph", "Graph Algorithms"),
                            ("array", "Array/List Operations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("code_implementation", models.TextField()),
                ("time_complexity", models.CharField(max_length=100)),
                ("space_complexity", models.CharField(max_length=100)),
                (
                    "data_structures",
                    models.ManyToManyField(
                        related_name="algorithms", to="visualizer.datastructure"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField()),
                ("steps", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(default="Untitled Visualization", max_length=200),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualizer.algorithm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
