# Generated by Django 5.0.1 on 2025-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="best_use_cases",
            field=models.TextField(
                blank=True, help_text="When this algorithm performs best"
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="educational_notes",
            field=models.TextField(
                blank=True,
                help_text="Detailed educational explanation of how the algorithm works",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="historical_context",
            field=models.TextField(
                blank=True, help_text="Historical development of the algorithm"
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="limitations",
            field=models.TextField(
                blank=True, help_text="Limitations or drawbacks of this algorithm"
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="step_by_step_explanation",
            field=models.TextField(
                blank=True,
                help_text="Written step-by-step explanation of the algorithm",
            ),
        ),
    ]
